In [ ]:
from google.colab import files

uploaded = files.upload()

Saving PRSA2017_Data_20130301-20170228.zip to PRSA2017_Data_20130301-20170228.zip

In [ ]:
import zipfile
import os

zip_file = "PRSA2017_Data_20130301-20170228.zip"

with zipfile.ZipFile(zip_file, 'r') as zip_ref:
    zip_ref.extractall("air_quality_dataset")

print("Dataset extracted successfully!")

Dataset extracted successfully!

In [ ]:
import os

dataset_path = "air_quality_dataset/PRSA_Data_20130301-20170228"

print(os.listdir(dataset_path))

['PRSA_Data_Wanshouxigong_20130301-20170228.csv', 'PRSA_Data_Wanliu_20130301-20170228.csv', 'PRSA_Data_Nongzhanguan_20130301-20170228.csv', 'PRSA_Data_Tiantan_20130301-20170228.csv', 'PRSA_Data_Huairou_20130301-20170228.csv', 'PRSA_Data_Dingling_20130301-20170228.csv', 'PRSA_Data_Aotizhongxin_20130301-20170228.csv', 'PRSA_Data_Changping_20130301-20170228.csv', 'PRSA_Data_Guanyuan_20130301-20170228.csv', 'PRSA_Data_Shunyi_20130301-20170228.csv', 'PRSA_Data_Dongsi_20130301-20170228.csv', 'PRSA_Data_Gucheng_20130301-20170228.csv']

In [ ]:
import pandas as pd
import glob
import os

csv_files = glob.glob(os.path.join(dataset_path, "*.csv"))

print("Number of CSV files:", len(csv_files))

df_list = []

for file in csv_files:
    df = pd.read_csv(file)
    df_list.append(df)

merged_df = pd.concat(df_list, ignore_index=True)

print("Datasets merged successfully!")

Number of CSV files: 12
Datasets merged successfully!

In [ ]:
print("Shape:", merged_df.shape)

merged_df.head()

Shape: (420768, 18)

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,9.0,9.0,6.0,17.0,200.0,62.0,0.3,1021.9,-19.0,0.0,WNW,2.0,Wanshouxigong
1,2,2013,3,1,1,11.0,11.0,7.0,14.0,200.0,66.0,-0.1,1022.4,-19.3,0.0,WNW,4.4,Wanshouxigong
2,3,2013,3,1,2,8.0,8.0,NaN,16.0,200.0,59.0,-0.6,1022.6,-19.7,0.0,WNW,4.7,Wanshouxigong
3,4,2013,3,1,3,8.0,8.0,3.0,16.0,NaN,NaN,-0.7,1023.5,-20.9,0.0,NW,2.6,Wanshouxigong
4,5,2013,3,1,4,8.0,8.0,3.0,NaN,300.0,36.0,-0.9,1024.1,-21.7,0.0,WNW,2.5,Wanshouxigong

In [ ]:
merged_df.isnull().sum()

No             0
year           0
month          0
day            0
hour           0
PM2.5       8739
PM10        6449
SO2         9021
NO2        12116
CO         20701
O3         13277
TEMP         398
PRES         393
DEWP         403
RAIN         390
wd          1822
WSPM         318
station        0
dtype: int64

In [ ]:
print("Duplicate Rows:", merged_df.duplicated().sum())

Duplicate Rows: 0

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420768 entries, 0 to 420767
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   No       420768 non-null  int64
 1   year     420768 non-null  int64
 2   month    420768 non-null  int64
 3   day      420768 non-null  int64
 4   hour     420768 non-null  int64
 5   PM2.5    412029 non-null  float64
 6   PM10     414319 non-null  float64
 7   SO2      411747 non-null  float64
 8   NO2      408652 non-null  float64
 9   CO       400067 non-null  float64
 10  O3       407491 non-null  float64
 11  TEMP     420370 non-null  float64
 12  PRES     420375 non-null  float64
 13  DEWP     420365 non-null  float64
 14  RAIN     420378 non-null  float64
 15  wd       418946 non-null  object
 16  WSPM     420450 non-null  float64
 17  station  420768 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 57.8+ MB

In [ ]:
merged_df.to_csv("Beijing_Air_Quality_Merged.csv", index=False)

print("Merged dataset saved successfully!")

Merged dataset saved successfully!

In [ ]:
from google.colab import files

files.download("Beijing_Air_Quality_Merged.csv")